-- 08_validate.sql
-- Health check queries for all 7 SPCS services.
-- Run after deployment to verify all services are READY.

USE ROLE ACCOUNTADMIN;
USE DATABASE AIRFLOW_DB;
USE SCHEMA AIRFLOW_SCHEMA;

-- Check status of all services
SELECT 'AF_POSTGRES' AS service, SYSTEM$GET_SERVICE_STATUS('AF_POSTGRES') AS status
UNION ALL
SELECT 'AF_REDIS', SYSTEM$GET_SERVICE_STATUS('AF_REDIS')
UNION ALL
SELECT 'AF_API_SERVER', SYSTEM$GET_SERVICE_STATUS('AF_API_SERVER')
UNION ALL
SELECT 'AF_SCHEDULER', SYSTEM$GET_SERVICE_STATUS('AF_SCHEDULER')
UNION ALL
SELECT 'AF_DAG_PROCESSOR', SYSTEM$GET_SERVICE_STATUS('AF_DAG_PROCESSOR')
UNION ALL
SELECT 'AF_TRIGGERER', SYSTEM$GET_SERVICE_STATUS('AF_TRIGGERER')
UNION ALL
SELECT 'AF_WORKERS', SYSTEM$GET_SERVICE_STATUS('AF_WORKERS');

-- Show compute pool status
SHOW COMPUTE POOLS LIKE 'INFRA_POOL';
SHOW COMPUTE POOLS LIKE 'CORE_POOL';
SHOW COMPUTE POOLS LIKE 'WORKER_POOL';

-- Show service endpoints (for accessing Airflow UI)
SHOW ENDPOINTS IN SERVICE AF_API_SERVER;

-- Show service logs (most recent from each service)
-- Uncomment to debug startup issues:
-- SELECT SYSTEM$GET_SERVICE_LOGS('AF_POSTGRES', 0, 'postgres', 50);
-- SELECT SYSTEM$GET_SERVICE_LOGS('AF_API_SERVER', 0, 'api-server', 50);
-- SELECT SYSTEM$GET_SERVICE_LOGS('AF_SCHEDULER', 0, 'scheduler', 50);
-- SELECT SYSTEM$GET_SERVICE_LOGS('AF_WORKERS', 0, 'worker', 50);
