-- 09_suspend_all.sql
-- Suspends all services and compute pools to stop credit consumption.
-- Order: services first, then compute pools.
-- Idempotent: uses IF EXISTS.

USE ROLE ACCOUNTADMIN;
USE DATABASE AIRFLOW_DB;
USE SCHEMA AIRFLOW_SCHEMA;

-- Suspend services (workers first, then core, then infra)
ALTER SERVICE IF EXISTS AF_WORKERS SUSPEND;
ALTER SERVICE IF EXISTS AF_TRIGGERER SUSPEND;
ALTER SERVICE IF EXISTS AF_DAG_PROCESSOR SUSPEND;
ALTER SERVICE IF EXISTS AF_SCHEDULER SUSPEND;
ALTER SERVICE IF EXISTS AF_API_SERVER SUSPEND;
ALTER SERVICE IF EXISTS AF_REDIS SUSPEND;
ALTER SERVICE IF EXISTS AF_POSTGRES SUSPEND;

-- Suspend compute pools (stops all nodes, no credit consumption)
ALTER COMPUTE POOL IF EXISTS WORKER_POOL SUSPEND;
ALTER COMPUTE POOL IF EXISTS CORE_POOL SUSPEND;
ALTER COMPUTE POOL IF EXISTS INFRA_POOL SUSPEND;

-- Verify all pools are suspended
SHOW COMPUTE POOLS LIKE '%_POOL';
