-- 10_resume_all.sql
-- Resumes all compute pools and services.
-- Order: compute pools first, then infra services, then core, then workers.
-- Idempotent: uses IF EXISTS.

USE ROLE ACCOUNTADMIN;
USE DATABASE AIRFLOW_DB;
USE SCHEMA AIRFLOW_SCHEMA;

-- Resume compute pools (starts MIN_NODES on each)
ALTER COMPUTE POOL IF EXISTS INFRA_POOL RESUME;
ALTER COMPUTE POOL IF EXISTS CORE_POOL RESUME;
ALTER COMPUTE POOL IF EXISTS WORKER_POOL RESUME;

-- Resume infrastructure services first
ALTER SERVICE IF EXISTS AF_POSTGRES RESUME;
ALTER SERVICE IF EXISTS AF_REDIS RESUME;

-- Resume core Airflow services
ALTER SERVICE IF EXISTS AF_API_SERVER RESUME;
ALTER SERVICE IF EXISTS AF_SCHEDULER RESUME;
ALTER SERVICE IF EXISTS AF_DAG_PROCESSOR RESUME;
ALTER SERVICE IF EXISTS AF_TRIGGERER RESUME;

-- Resume workers last
ALTER SERVICE IF EXISTS AF_WORKERS RESUME;

-- Verify status
SELECT 'AF_POSTGRES' AS service, SYSTEM$GET_SERVICE_STATUS('AF_POSTGRES') AS status
UNION ALL
SELECT 'AF_REDIS', SYSTEM$GET_SERVICE_STATUS('AF_REDIS')
UNION ALL
SELECT 'AF_API_SERVER', SYSTEM$GET_SERVICE_STATUS('AF_API_SERVER')
UNION ALL
SELECT 'AF_SCHEDULER', SYSTEM$GET_SERVICE_STATUS('AF_SCHEDULER')
UNION ALL
SELECT 'AF_DAG_PROCESSOR', SYSTEM$GET_SERVICE_STATUS('AF_DAG_PROCESSOR')
UNION ALL
SELECT 'AF_TRIGGERER', SYSTEM$GET_SERVICE_STATUS('AF_TRIGGERER')
UNION ALL
SELECT 'AF_WORKERS', SYSTEM$GET_SERVICE_STATUS('AF_WORKERS');
